suggestion_generation:
  description: >
    Analyze the provided CSV data and generate actionable insights.
    Focus on:
    - Key patterns and trends in the data
    - Significant correlations
    - Anomalies or areas of concern
    - Actionable recommendations based on findings
  expected_output: >
    A detailed analysis with clear, actionable suggestions based on
    the data patterns identified.

table_generation:
  description: >
    Create summary tables from the analyzed data that highlight:
    - Key metrics and their trends
    - Important correlations
    - Performance indicators
    - Comparative analysis where relevant
    
    Format tables in markdown for clear presentation.
  expected_output: >
    A set of well-formatted markdown tables presenting key data insights.

chart_generation:
  description: >
    Generate visual representations of the data including:
    - Trend analysis charts
    - Distribution plots
    - Comparison charts
    - Key metric visualizations
    
    Save charts as image files and provide markdown references.
  expected_output: >
    A collection of charts saved as image files with markdown references
    for inclusion in the final report.

final_report_assembly:
  description: >
    Compile a comprehensive report that includes:
    - Executive summary
    - Key findings and insights
    - Data visualization (charts and tables)
    - Recommendations and next steps
    
    Save the final report as 'finalreport.md' in the reports directory.
  expected_output: >
    A complete markdown report saved as 'finalreport.md' that integrates
    all analyses, visualizations, and recommendations.









